<?php

use  \Drupal\Core\Form\FormStateInterface;

function webspark_blocks_theme_suggestions_block_alter(array &$suggestions, array $variables) {

  // Block suggestions for custom block bundles.
  if (isset($variables['elements']['content']['#block_content'])
    && $variables['elements']['content']['#block_content'] instanceof BlockContentInterface) {
    $blockType = $variables['elements']['content']['#block_content']->bundle();
    $view_mode = strtr($variables['elements']['#configuration']['view_mode'], '.', '_');
    $suggestions[] = 'block__' . $blockType;
    $suggestions[] = 'block__' . $blockType . '__' . $view_mode;
  }
}

function webspark_blocks_form_block_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  _webspark_blocks_title($form);
}

function webspark_blocks_form_layout_builder_add_block_alter(&$form, FormStateInterface $form_state, $form_id) {
  _webspark_blocks_title($form);
}

function _webspark_blocks_title(&$form){
  $form['settings']['label_display']['#default_value'] = FALSE;
  $form['settings']['label']['#title'] = t('Block admin title');
}

/**
 * Implements hook_page_attachments().
 */
function webspark_blocks_page_attachments(array &$attachments) {
  $attachments['#attached']['library'][] = 'webspark_blocks/webspark_blocks';
}